name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: cargo deb
      run: cargo install cargo-deb
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build deb
      run: cargo deb
    - name: Upload release
      uses: actions/upload-artifact@v2
      with:
        name: amd64deb
        path: ./target/debian/*.deb
